### ISSUE TITLE
License

### ISSUE THREAD

**Issue by crobibero** [aksoftware98/tailwind_blazor_transition#1]
Hi, I would like to use this library but it is currently unlicensed. Can you please specify what license you have this published under?

A good resource for this is https://choosealicense.com/

Thanks in advance!

**Comment by aksoftware98** [comment]
Hi 
Thanks for reaching out, this library is not under any license but basically, it's MIT, I will make sure to update that, but in general, you are 100% free to do whatever you want with ti

Thank you

**Comment by aksoftware98** [comment]
The license file has been set in a new version 1.1.0, so now the package has the MIT license 
Thanks for mentioning
In case you have any issue feel free to create a new issue
