### ISSUE TITLE
Why are those Task.Delays needed?

### ISSUE THREAD

**Issue by rondegroot** [aksoftware98/tailwind_blazor_transition#4]
https://github.com/aksoftware98/tailwind_blazor_transition/blob/2e82b17c4e45abb50cd5e60f349dbba387ee0353/src/AKSoftware.Blazor.TailwindTransition/TWTransitionalComponentBase.cs#L51

I tested with Task.Delay(1), which is also working fine. But I'm wondering why these Delays are needed in the first place. Could you please clarify this?

Regards, Ron

**Comment by aksoftware98** [comment]
Okay that's a very good question, actually developing this little package was a little bit tricky so I added those some delays here and there just to make sure that it holds on to the operation until the class with the transaction takes effect, but actually maybe if we test it very well, we can remove them.

Thank for mentioning that

**Comment by rondegroot** [comment]
Yeah, I tried some things like StateHasChanges, await Task.Completed and Task.Delay(1). Only the last one is working.

**Comment by rondegroot** [comment]
await Task.Yield(); is also working

**Comment by rondegroot** [comment]
https://stackoverflow.com/a/61566992

**Comment by aksoftware98** [comment]
Thank you so much for this effort, will take that into consideration and work on cleaning the code more.
Thanks for your contribution,
